name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (if needed)
      - name: Set up Node.js (if using JS)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Run build or test commands
      - name: Run tests
        run: |
          echo "Run your tests here (e.g., npm test)"

      # Step 4: Deploy (optional - GitHub Pages in this case)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Path to deploy (e.g., where your index.html is)
